config/routes.rb
Babe::Application.routes.draw do
  

  get "account/avatar" => "profile#avatar"
  patch "account/avatar" => "profile#upload"
  get "account/password" => "profile#edit"
  put "account/password" => "profile#update"
  get "account/addition" => "profile#addition"
  post "account/addition" => "profile#save"
  post "account/cover" => "profile#cover"

  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => :oauths
  }

  root 'home#index'

  get '/search/:word' => 'home#search', as: 'search'
  get '/about/:slug' => 'help#about', as: 'about'
  get '/help/:slug(/:page)' => 'help#view', as: 'help'

  resources :photos
  resources :comments

  get 'explore/:first(/:second(/:third))' => "categories#index", as: 'explore'

  resources :styles do
    member do
      post 'like'
    end
  end

  resources :bookmark

  resources :items do
    member do
      post 'like'
      delete 'like' => 'items#unlike'
      get 'favorites' => 'bookmark#new'
      post 'favorites' => 'items#favorites'
    end

    collection do
      get 'fetch'
      get 'fans'
      get 'more'
    end
  end

  resources :topics, :path => 'forum' do
    collection do
      get 'node/:id' => 'topics#node', as: 'node'
      get 'topic/:id' => 'topics#show', as: 'topic'
    end
  end

  namespace :cpanel do
    
    root :to => "home#index"
    
    resources :categories, path: 'category'

    resources :sections
    resources :nodes
    resources :topics
    resources :styles do
      collection do
        post 'cancel'
        post 'remove'
        post 'recommend'
      end
    end
    resources :positions
    resources :ads
    resources :catalogs
    resources :pages
    resources :tags

    resources :users do
      collection do
        get 'admin'
      end
    end
    
    resources :tasks do
      collection do
        post 'fetch'
        get 'promotion'
        get 'todaypromo'
        post 'recommend'
        post 'cancel'
      end
    end

    resources :items do
      collection do
        post 'remove'
        post 'cancel'
        post 'moveto'
        post 'free'
        post 'band'
        post 'bind'
        get 'tags'
        post 'pin'
      end
    end
  end

  get "users", :to => "users#index", :as => :users
  
  resources :users, :path => "" do
    member do
      get :items
      get :likes
      get :followers
      get :following
      get :topics
    end

    post "follow" => :follow
    delete "follow" => :unfollow
  end

  

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessor :photo

  belongs_to :node, counter_cache: true
  belongs_to :user, counter_cache: true
  has_many :photos, :as => :subject
  has_many :comments, :as => :subject

  validates_presence_of :user_id, :title, :body, :node_id

  after_save :binding_photo_to_this

  scope :fields_in_list, -> { select(Topic.attribute_names - ['body']) }

  protected

  def binding_photo_to_this
    if self.photo and self.photo.has_key?(:id) and self.photo[:id].is_a?(Array)
      Photo.update_all({subject_id: self.id, subject_type: 'Topic'}, ["id in (?)", self.photo[:id]])
    end
  end
end

app/controllers/cpanel/topics_controller.rb
# coding: utf-8
class Cpanel::TopicsController < Cpanel::ApplicationController

  def index
    @topics = Topic.order('id desc').includes(:user).paginate :page => params[:page], :per_page => 30

  end

  def show
    @topic = Topic.unscoped.find(params[:id])

  end


  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.unscoped.find(params[:id])
  end

  def create
    @topic = Topic.new(params[:topic].permit!)

    if @topic.save
      redirect_to(cpanel_topics_path, :notice => 'Topic was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @topic = Topic.unscoped.find(params[:id])

    if @topic.update_attributes(params[:topic].permit!)
      redirect_to(cpanel_topics_path, :notice => 'Topic was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @topic = Topic.unscoped.find(params[:id])
    @topic.destroy_by(current_user)

    redirect_to(cpanel_topics_path)
  end

  def undestroy
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:deleted_at, nil)
    redirect_to(cpanel_topics_path)
  end

  def suggest
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:suggested_at, Time.now)
    CacheVersion.topic_last_suggested_at = Time.now
    redirect_to(cpanel_topics_path, :notice => "Topic:#{params[:id]} suggested.")
  end

  def unsuggest
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:suggested_at, nil)
    CacheVersion.topic_last_suggested_at = Time.now
    redirect_to(cpanel_topics_path, :notice => "Topic:#{params[:id]} unsuggested.")
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create, :edit]
  before_action :find, except: [:index, :create, :new]

  def index
    @topics = Topic.all.includes(:photos).order('id desc')
    @sections = Section.includes(:nodes).order('sort asc')
    @users = User.order('topics_count desc').limit(10)
  end

  def node
    @node = Node.find(params[:id])
    @section = @node.section
    @nodes = @section.nodes
    @sections = Section.includes(:nodes).order('sort asc')
    @topics = @node.topics
    @users = []
  end

  def new
    @topic = Topic.new
  end

  def show
    @links = Topic.where(node_id: @topic.node_id).order('created_at desc').limit(10)
  end

  def create
    @topic = Topic.new(topic_params)

    @topic.user_id = current_user.id
    @topic.node_id = params[:node] || topic_params[:node_id]
    #@topic.photo = params[:photo] || topic_params[:photo]

    if @topic.save
      redirect_to(topic_path(@topic.id), :notice => t("topics.create_topic_success"))
    else
      render :action => "new"
    end
  end

  protected

  def find
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :body, :node_id, :photo => {:id => []})
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def render_topic_node_select_tag(topic)
    return if topic.blank?
    grouped_collection_select :topic, :node_id, Section.all,
                    :sorted_nodes, :name, :id, :name, {:value => topic.node_id,
                    :include_blank => true, :prompt => "选择节点"}, :style => "width:145px;"
  end
end

app/views/topics/_form.html.erb
<%= content_for :styles do %>

<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/scripts/jquery-file-uploader/css/jquery.fileupload.css">
<link href="/scripts/editor/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="/scripts/editor/css/froala_editor.min.css" rel="stylesheet" type="text/css">
<% end %>

<div class="container" id="main">
    <div class="row new">
        <div class="col-md-8 edit">
        <%= simple_form_for @topic, html:{id: "fileupload", class: 'form-horizontal',role: "form"}  do |f| %>
          
          <%= render "shared/error", :target => @topic %>  

          <div class="form-group">
            <label for="topic_node_id" class="col-sm-2 control-label">选择主题</label>
            <div class="col-sm-10">
              <%= render_topic_node_select_tag(@topic) %>
            </div>
          </div>

          <div class="form-group">
            <label for="title" class="col-sm-2 control-label">标题</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="title" name="topic[title]" placeholder="标题">
            </div>
          </div>

          <div class="form-group">
            <label for="title" class="col-sm-2 control-label"></label>
            <div class="col-sm-10" id="files">
              
            </div>
          </div>

          <div class="form-group">
            <label for="fileupload" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
              <input type="file" class="form-control" name="files[]"  />
            </div>
          </div>

          <div class="form-group">
            <label for="text" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
              <textarea name="topic[body]" id="text"></textarea>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">发表</button>
            </div>
          </div>
           
        <% end %>
        </div>

        <div class="col-md-4 sider">
            <ul>
                <li> user info </li>
            </ul>
        </div>
    </div>
</div>

<%= content_for :scripts do %>
<script src="/scripts/jquery-file-uploader/js/vendor/jquery.ui.widget.js"></script>
<script src="/scripts/jquery-file-uploader/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/scripts/jquery-file-uploader/js/jquery.fileupload.js"></script>
<script src="/scripts/editor/js/froala_editor.min.js"></script>
<script src="/scripts/editor/js/langs/zh_cn.js"></script>
<script>
$(function () {
    'use strict';
    // Change this to the location of your server-side upload handler:
    var url =  '/photos';
    $('#fileupload').fileupload({
        url: url,
        dataType: 'json',
        done: function (e, data) {
            $.each(data.result.files, function (index, file) {
                //$('<p/>').text(file.name).appendTo('#files');
                var html = '<dl><dt><img src="'+ file.url +'" width="100" /></dt>';
                    html += '<dd><input type="hidden" name="topic[photo][id][]" value="'+ file.id +'" />'+ file.name +'</dd></dl>';
                $('#files').append( html );
            });
        },
        progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress .progress-bar').css(
                'width',
                progress + '%'
            );
        }
    }).prop('disabled', !$.support.fileInput)
        .parent().addClass($.support.fileInput ? undefined : 'disabled');

    $.Editable.prototype.parseImageResponse = function(d){
  var json = $.parseJSON(d);
  try{
    this.writeImage(json.link);
    var html = '<dl><dt><img src="'+ json.thumbnail_url +'" width="100" /></dt>';
        html += '<dd><input type="hidden" name="topic[photo][id][]" value="'+ json.id +'" />'+ json.name +'</dd></dl>';
        $('#files').append( html );
  }catch (d) {
    this.throwImageError(4)
  }
}

$('#text').editable({inlineMode: false, 
  language: 'zh_cn',
  placeholder: '开始输入...',
  minHeight: 150,
  mediaManager: false,
  maxImageSize: 1024 * 1024 * 3,
  imageUploadParam: 'files[]',
  imageUploadParams: {authenticity_token: $('input[name="authenticity_token"]').val()},
  imageDeleteURL: 'http://example.com/delete_image',
  imageUploadURL: "<%= photos_path %>",
  borderColor: '#ccc',
  buttons: ['bold', 'fontSize', 'color', 'item', 'insertImage', 'insertVideo'], 
  blockTags: ['p'],
  
  customButtons: {
    item: {
      title: '宝贝',
      icon: {
        type: 'font',
        value: 'fa fa-shopping-cart'
      },
      callback: function (editor){
        alert ('Hello!')
      }
    }
  }
});
});
</script>
<% end %>

app/views/topics/_section.html.erb
<ul class="section">
  <li>
    <%= link_to section.name, '' %>
    <ol class="node">
    <% section.nodes.each do |node| %>
      <li><%= link_to node.name, node_topics_path(node)%></li>
    <% end %>
    </ol>
  </li>
</ul>

app/views/topics/_topic.html.erb
<div class="topic clearfix">
  <div class="node">
    <div class="type round-sm">问答</div>
    
    <div class="reply">
      <div class="count">250</div>
      <div class="name">回复</div>
    </div>    
  </div>

  <div class="summary">
    <h3><%=link_to topic.title, topic_topics_path(topic) %></h3>
    <div class="user">
      <%= link_to topic.user.name, user_path(topic.user.login) %>
      发表于 <span class="time"><%= topic.created_at.strftime("%H:%M:%S") %>
      浏览1233 / 喜欢1233
    </div>
    <div class="text"><%= truncate(topic.body, length: 140) %></div>
    <ul class="thumb clearfix">
      <% topic.photos.each do |photo| %>
      <li ><%= image_tag photo.file.url, width: '200' %></li>
      <% end %>
    </ul>
  </div>
</div>
    

app/views/topics/edit.html.erb
<%= render 'form' %>

app/views/topics/index.html.erb
<div class="container" id="main">
  <div class="row">    
    <div class="col-md-8 list">
      <div class="toolbar">
        <a href="">全部</a>
        <span class="sparator">-</span>
        <a href="">精华</a>
        <span class="sparator">-</span>
        <a href="">知识</a>
        <span class="sparator">-</span>
        <a href="">问答</a>

        <span class="sparator">|</span>

        <a href="">最新</a>
        <span class="sparator">-</span>
        <a href="">最多回复</a>
      </div>
      <div class="topics">
        <%= render partial: 'topic', collection: @topics %>
      </div>
    </div>

    <div class="col-md-4 sider">
      <div class="new">
        <%= link_to new_topic_path do %>
        <span class="round box"><i class="glyphicon glyphicon-edit"></i>发表新话题</span>
        <% end %>
        <a href="">
          <span class="round box"><i class="glyphicon glyphicon-edit"></i>申请新主题</span>
        </a>
      </div>

      <div class="category">
        <% @sections.each do |section| %>
        <ul class="section">
          <li>
            <%= link_to section.name, '' %>
            <ol class="node">
            <% section.nodes.each do |node| %>
              <li><%= link_to node.name, ''%></li>
            <% end %>
            </ol>
          </li>
        </ul>
        <% end %>
      </div>

      <div class="users">
        <div class="hd"><h5>活跃用户</h5></div>
        <ul>
          <% @users.each do |user| %>
          <li><%=user_avatar_tag(user, :normal) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<%= render 'form' %>

app/views/topics/node.html.erb
<div class="container" id="main">
  <div class="row">    
    <div class="col-md-8 list">
      <div class="node">
        <%= @node.name %>
      </div>

      <div class="toolbar">
        <a href="">全部</a>
        <span class="sparator">-</span>
        <a href="">精华</a>
        <span class="sparator">-</span>
        <a href="">知识</a>
        <span class="sparator">-</span>
        <a href="">问答</a>

        <span class="sparator">|</span>

        <a href="">最新</a>
        <span class="sparator">-</span>
        <a href="">最多回复</a>
      </div>

      <div class="topics">
        <%= render partial: 'topic', collection: @topics %>
      </div>
    </div>

    <div class="col-md-4 sider">
      <div class="new">
        <div class="">
          <%= link_to new_topic_path do %>
          <i class="glyphicon glyphicon-edit"></i>发表新话题
          <% end %>
        </div>
        <div class="">
          <a href="">
           <i class="glyphicon glyphicon-tasks"></i>申请新主题
          </a>
        </div>
      </div>

      <div class="category clearfix">
        <div class="hd"><h5><i class="glyphicon glyphicon-list"></i>主题</h5></div>
        <%= render partial: 'section', collection: @sections %>
      </div>

      <div class="users">
        <div class="hd"><h5>活跃用户</h5></div>
        <ul>
          <% @users.each do |user| %>
          <li><%=user_avatar_tag(user, :normal) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container" id="main">
  <div class="row topics">
    <div class="col-md-8 list">
      <div class="topic">
        <h1><%= @topic.title %></h1>

        <div class="context">
          <%= raw @topic.body %>
        </div>

        <div class="comment">
          <%= render 'comments/comment', target: @topic  %>
        </div>
      </div>
    </div>

    <div class="col-md-4 sider">
      <div class="new">
        <%= link_to new_topic_path do %>
        <span class="round box"><i class="glyphicon glyphicon-edit"></i>发表新话题</span>
        <% end %>
      </div>

     
      <%= render 'items/user', target: @topic.user %>

      <div class="recommend clearfix">
        <div class="hd">相关</div>
        <ul class="">
          <% @links.each do |link| %>
          <li><%= link_to link.title, topic_topics_path(link) %></li>
          <% end %>
        </ul>
      </div>

      <div class="follow">
        
      </div>
    </div>
  </div>
</div>