config/routes.rb
Babe::Application.routes.draw do
  

  get "account/avatar" => "profile#avatar"
  patch "account/avatar" => "profile#upload"
  get "account/password" => "profile#edit"
  put "account/password" => "profile#update"
  get "account/addition" => "profile#addition"
  post "account/addition" => "profile#save"
  post "account/cover" => "profile#cover"

  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => :oauths
  }

  root 'home#index'

  get '/search/:word' => 'home#search', as: 'search'
  get '/about/:slug' => 'help#about', as: 'about'
  get '/help/:slug(/:page)' => 'help#view', as: 'help'

  resources :photos
  resources :comments

  get 'explore/:first(/:second(/:third))' => "categories#index", as: 'explore'

  resources :styles do
    member do
      post 'like'
    end
  end

  resources :bookmark

  resources :items do
    member do
      post 'like'
      delete 'like' => 'items#unlike'
      get 'favorites' => 'bookmark#new'
      post 'favorites' => 'items#favorites'
    end

    collection do
      get 'fetch'
      get 'fans'
      get 'more'
    end
  end

  resources :topics, :path => 'forum' do
    collection do
      get 'node/:id' => 'topics#node', as: 'node'
      get 'topic/:id' => 'topics#show', as: 'topic'
    end
  end

  namespace :cpanel do
    
    root :to => "home#index"
    
    resources :categories, path: 'category'

    resources :sections
    resources :nodes
    resources :topics
    resources :styles do
      collection do
        post 'cancel'
        post 'remove'
        post 'recommend'
      end
    end
    resources :positions
    resources :ads
    resources :catalogs
    resources :pages
    resources :tags

    resources :users do
      collection do
        get 'admin'
      end
    end
    
    resources :tasks do
      collection do
        post 'fetch'
        get 'promotion'
        get 'todaypromo'
        post 'recommend'
        post 'cancel'
      end
    end

    resources :items do
      collection do
        post 'remove'
        post 'cancel'
        post 'moveto'
        post 'free'
        post 'band'
        post 'bind'
        get 'tags'
        post 'pin'
      end
    end
  end

  get "users", :to => "users#index", :as => :users
  
  resources :users, :path => "" do
    member do
      get :items
      get :likes
      get :followers
      get :following
      get :topics
    end

    post "follow" => :follow
    delete "follow" => :unfollow
  end

  

end

app/views/shared/_error.html.erb
<% if target.errors.any? %>  
 <div class="alert alert-danger alert-dismissable">
   <a class="close" data-dismiss='alert' href="#">×</a>
   <p><strong>有 <%= target.errors.count %> 处问题导致无法提交:</strong></p>
   <ul>
   <% target.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row one">
      <div class="col-md-2">
        <h3><a href="/" class="logo"></a></h3>
      </div>
      <div class="col-md-6">
        <div class="serial">
          <h3>公司</h3>
          <%= render_about_links %>
        </div>

        <div class="serial">
          <h3>社区</h3>
          <ul>
            <li><a href="#">问答</a></li>
            <li><a href="#">主题</a></li>
            <li><a href="#">推广</a></li>
          </ul>
        </div>

        <div class="serial">
          <h3>帮助</h3>
          <ul>
            <li><a href="#">进入社区讨论</a></li>
            <li><a href="#">如何发布单品</a></li>
            <li><a href="#">如何发布搭配</a></li>
            <li><a href="#">如何申请达人</a></li>
          </ul>
        </div>
      </div>

      <div class="col-md-4">
        <h3>分享</h3>
        <div class="share">
          <a href="#" title="关注宝贝丁微博" class="att_weibo" target="_blank"></a>
          <a href="#" title="关注宝贝丁空间" class="att_zone" target="_blank"></a>
          <a href="#" title="关注宝贝丁微信" class="att_weixin" target="_blank"></a>
          <!-- <a href="javascript:;" title="扫码" class="att_code"></a> -->
        </div>
      </div>
    </div>

    <div class="row two">
      <div class="col-md-12">
        <p> © 厦门快鱼信息技术有限公司  保留所有解释权</p>
      </div>
    </div>
  </div>
</div>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?1f3023f0dd4f4841dc7f13113cd1d93d";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

app/views/shared/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top" role="banner">
  <div class="container">
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%=link_to t('common.publish'), new_item_path, class: 'share' %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.name%><b class="caret"></b></a>
          <%= render_list :class => "dropdown-menu" do |li|
              li << link_to(t("common.my_home"), user_path(current_user.login) )
              li << link_to(t("common.edit_account"), edit_user_registration_path)
              if current_user and current_user.try(:admin)
              li << link_to(t('common.cpanel'), cpanel_root_path) 
              end
              li << link_to(t("users.signout"), destroy_user_session_path, method: "delete" )
            end %>
        </li>
        <% else %>
        <li><%= link_to t('users.signin'), new_user_session_path %> </li>
        <li><%= link_to t('users.signup'), new_user_registration_path %> </li>
        <% end %>
        <li><a href="/help">帮助中心</a></li>
        <li><a>收藏</a></li>
      </ul>
    </nav>
  </div>
</header>

<div class="search">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h5><a href="/" class="logo"></a></h5>
      </div>
      <div class="col-md-9">
        <div class="form">
          <div class="input-group">
            <i class="glyphicon glyphicon-search"></i>
            <input type="text" class="form-control" placeholder="妈妈去哪买衣服?">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">搜索</button>
            </span>          
          </div>
          <div class="keywords">
           <% Tag.keywords.each do |tag| %>
           <%= link_to tag.name,search_path(tag.name) %>
           <% end %>
          </div>              
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<%= link_to t("users.sigin"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t("users.signup"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to t("users.forget_password"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t("users.not_recieve_confirm_mail"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t("users.not_recieve_confirm_mail"), new_unlock_path(resource_name) %><br />
<% end -%>

app/views/shared/_menu.html.erb
<%= render_list class: 'nav nav-justified' do |li|
  
  Category.roots.each do |c|
    li << link_to(c.name, explore_path(c.slug))
    #li << %Q( #{a} <i class="bar">|</i> )
    li << '<i class="bar">|</i>'
  end

  li << link_to(t('common.styles'), '#')
  li << '<i class="bar">|</i>'
  li << link_to(t('common.community'),  '#')
  li << '<i class="bar">|</i>'
  li << link_to(t('common.groupon'), '#')
end
%>