config/routes.rb
Babe::Application.routes.draw do
  

  get "account/avatar" => "profile#avatar"
  patch "account/avatar" => "profile#upload"
  get "account/password" => "profile#edit"
  put "account/password" => "profile#update"
  get "account/addition" => "profile#addition"
  post "account/addition" => "profile#save"
  post "account/cover" => "profile#cover"

  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => :oauths
  }

  root 'home#index'

  get '/search/:word' => 'home#search', as: 'search'
  get '/about/:slug' => 'help#about', as: 'about'
  get '/help/:slug(/:page)' => 'help#view', as: 'help'

  resources :photos
  resources :comments

  get 'explore/:first(/:second(/:third))' => "categories#index", as: 'explore'

  resources :styles do
    member do
      post 'like'
    end
  end

  resources :bookmark

  resources :items do
    member do
      post 'like'
      delete 'like' => 'items#unlike'
      get 'favorites' => 'bookmark#new'
      post 'favorites' => 'items#favorites'
    end

    collection do
      get 'fetch'
      get 'fans'
      get 'more'
    end
  end

  resources :topics, :path => 'forum' do
    collection do
      get 'node/:id' => 'topics#node', as: 'node'
      get 'topic/:id' => 'topics#show', as: 'topic'
    end
  end

  namespace :cpanel do
    
    root :to => "home#index"
    
    resources :categories, path: 'category'

    resources :sections
    resources :nodes
    resources :topics
    resources :styles do
      collection do
        post 'cancel'
        post 'remove'
        post 'recommend'
      end
    end
    resources :positions
    resources :ads
    resources :catalogs
    resources :pages
    resources :tags

    resources :users do
      collection do
        get 'admin'
      end
    end
    
    resources :tasks do
      collection do
        post 'fetch'
        get 'promotion'
        get 'todaypromo'
        post 'recommend'
        post 'cancel'
      end
    end

    resources :items do
      collection do
        post 'remove'
        post 'cancel'
        post 'moveto'
        post 'free'
        post 'band'
        post 'bind'
        get 'tags'
        post 'pin'
      end
    end
  end

  get "users", :to => "users#index", :as => :users
  
  resources :users, :path => "" do
    member do
      get :items
      get :likes
      get :followers
      get :following
      get :topics
    end

    post "follow" => :follow
    delete "follow" => :unfollow
  end

  

end

app/controllers/cpanel/home_controller.rb
class Cpanel::HomeController < Cpanel::ApplicationController
  def index
    
  end
end

app/controllers/home_controller.rb
# coding: utf-8

class HomeController < ApplicationController
  
  def index
    @slider = Ad.includes(:position).where("positions.slug= 'homepage slider'").references(:positions).limit(4)
    @items  = Item.pins.fields_in_list.limit(40).includes([:user, :comments]).order('id desc')
    @styles = Style.last.limit(5).includes([:user,:photos])
    @promotions = Promotion.pins.order('id desc').limit(10)

    set_seo_meta(Settings.seo.title, Settings.seo.keywords, Settings.seo.description)
  end

  def search
    render text: "comming soon!"
  end

end

app/views/home/_item.html.erb
<li>
  <div class="cover">
  <%= link_to item.url, target: '_blank' do %>
  <%= image_tag item.cover, alt: "#{item.title} 天天特价 #{item.mprice} 包邮" %>
  <% end %>
  </div>
  <div class="title"><%= link_to item.title, item.url, target: '_blank' %></div>
  <div class="price">

    <em >&yen;</em>
    <span ><del><%= item.mprice %></del></span>
    <span class="free"><%= sprintf("%2.1f", item.price / item.mprice * 10) %>折</span>
    <em class="yen">&yen;</em>
    <strong><%= item.price %></strong>
    <span class="free">包邮</span>

  </div>
</li>

app/views/home/_nav.html.erb
 <div class="primary_main">
 <div class="primary_nav_wrap" id="primaryNav">
    <!-- 类目导航 -->
    <h4 class="primary_nav_t">潮流单品<i>Shopping</i></h4>

    <ul class="primary_navlist">
        <script id="template-nav" type="text/x-tmpl">
        {% for(var i=0, e = o.tree.length; i < e; i++) { %}
        <li class="primary_navlist_li nav_top" data-tag="{%= i +1 %}">
            <div class="primary_navlist_wrap">
                <a href="/explore/{%= o.tree[i].slug%}" target="_blank" class="primary_navlist_icon">
                    <img src="http://s12.mogujie.cn/pic/140211/mea1_kqzgmokwkrbf6v2ugfjeg5sckzsew_50x50.jpg" alt="" width="50" height="50">
                </a>
                <h5 class="clearfix">
                    <a href="/explore/{%=o.tree[i].slug%}" target="_blank" class="primary_navlist_h fl mr10">{%= o.tree[i]['name'] %}</a>
                    <i class="primary_navtip fl">
                        <a href="/explore/" target="_blank" class="primary_navtip">
                        早春新品 限时折扣
                        </a>
                    </i>
                </h5>
                <ul class="primary_navsublist clearfix">
                    {% for(var j=0, k=o.tree[i].child.length; j < k ; j++) { %}
                    <li> <a href="/explore/{%=o.tree[i].slug%}/{%= o.tree[i].child[j].slug%}" target="_blank">{%= o.tree[i].child[j].name %}</a> </li>
                    {% } %}
                </ul>
                <i class="primary_nav_arw"></i>
            </div>
            <i class="primary_nav_borderbtm"></i>
            <i class="primary_nav_borderright"></i>
        </li>
        {% } %}
        </script>
    </ul>
</div>
</div>

app/views/home/_style.html.erb
<div class="zoom col-md-3">
  <% first = @styles.first %>
  <%= image_tag first.photos.first.file.url , size: '310x485' %>
</div>
<div class="fitness col-md-9">
  <div class="hot">
    <% @styles.each do |style|%>
    <div class="fit">
      <%= link_to style_path(style.id) do %>
        <%= image_tag style.photos.first.file.url, size: '120x360' %>
        <p class="ft">某系</p>
        <p class="user">某人</p>
      <% end %>
    </div>
    <% end %>
  </div>

  <div >
    <div class="hd"></div>
    <div class="bd">
      <% 3.times do %>
        <div class="place">场合推荐</div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div id="slider" class="carousel slide slider" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#slider" data-slide-to="0" class="active"></li>
    <li data-target="#slider" data-slide-to="1"></li>
    <li data-target="#slider" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @slider.each_with_index do |ad,index| %>
    <div class="item <%= 0 == index ? 'active': ''%>">
      <%= link_to ad.url do %>
      <%= image_tag ad.cover.default.url %>
      <% end %>
    </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#slider" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#slider" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-12 cat">
      <ul class="first sub "></ul>
    </div>
  </div>
</div>

<div id="special">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <!--<div class="hd clearfix"><h3><img src="/images/hot.png" /></h2></div>-->
        <ul>
          <li style="margin-left:0;"><img src="/images/10.png" /></li>
          <li><img src="/images/style.png" /></li>
          <li><img src="/images/community.png" /></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div id="promotion">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="hd clearfix"><h3><img src="/images/worthbuying.png" /></h2></div>
        <ul>
          <%= render partial: 'item', collection: @promotions %>
        </ul>
      </div>
    </div>
  </div>
</div>
<!--
<div id="recommend">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="hd clearfix"><h3><img src="/images/collection.png" alt="编辑推荐"/></h2></div>
      </div>
    </div>
  </div>
</div>
-->
<div class="list">
  <div class="container">
    <div class="row">
      <div class="col-md-12 clearfix">
        <div class="hd clearfix"><h3><img src="/images/whatsnew.png" alt="新上单品" /></h2></div>
        <ul class="items clearfix">
          <%= render partial: 'items/item', collection: @items %>
        </ul>
        <div style="display:none; position: absolute; bottom:10px;left:49%" id="loading"><h3>努力加载中...</h3></div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 end">
        <ol class="dot">
          <li ></li>
          <li class="active"></li>
          <li ></li>
        </ol>
        <div class="more">
          <a href="/explore/clothes" class="btn btn-success btn-lg">浏览更多</a>
        </div>
      </div>
    </div>
  </div>
</div>

<%= content_for :scripts do %>
<script id="template-nav" type="text/x-tmpl">
{% for(var i=0, e = o.tree.length; i < e; i++) { %}
<li data-tag="{%= i + 1 %}" class="{%= i == e - 1 ? 'last' : '' %}{%= 0 == i ? 'first' : '' %}">
  <div class="icon"><img src="/images/{%=o.tree[i].slug%}.png" /></div>
  <div class="item">
    <h3 class="title">
        <a href="/explore/{%=o.tree[i].slug%}" target="_blank" class="primary_navlist_h fl mr10">{%= o.tree[i]['name'] %}</a>
    </h3>
    <ol class="secondary clearfix">
        {% for(var j=0, k=o.tree[i].child.length; j < k ; j++) { %}
        <li> <a href="/explore/{%=o.tree[i].slug%}/{%= o.tree[i].child[j].slug%}" target="_blank">{%= o.tree[i].child[j].name %}</a> </li>
        {% } %}
    </ol>
  </div>
</li>
{% } %}
</script>

<script src="/scripts/category.json"></script>
<script src="/scripts/tmpl.min.js"></script>
<script type="text/javascript">

$(document).ready(function(){
  var $nav = $('.sub');
      $nav.append( tmpl('template-nav', tree) );

  window.onscroll = more;

  var loading = false, page = 2;

  function more(){
    if (!loading){
      if( $(document).scrollTop() + $(window).height() > $(document).height() - 200) {
        //show loading
        //console.log($(document).scrollTop() + $(window).height());
        loading = true;
        $('#loading').show();

        $.ajax({
          url: '/items/more',
          data: {page: ++page},
          success: function(html){
            //unbind the scroll
            $('.items').append( html );
            //resort the waterfall
            //waiting all images load
            var images = $('img', html), t = images.length;
 
            for(var i=0, e=t; i < e; i++){
              img = new Image();
              img.src = images[i].src;
              //cached images
              if(img.complete) --t;
              //new images
              img.onload = function(){
                --t;
              }
            }
            if(t == 0) waterFall();

            $('#loading').hide();
            loading = false;
            
            if (page > 5){
              window.onscroll = false;
              loading = true;
              // show explore more
              $('.list .end').show();
            }
          }
        });
      }
    }
  }
  //$('.fit').hover(function(){$(this).addClass('hover');},function(){$(this).removeClass('hover');})
});

</script>
<% end %>