config/routes.rb
Babe::Application.routes.draw do
  

  get "account/avatar" => "profile#avatar"
  patch "account/avatar" => "profile#upload"
  get "account/password" => "profile#edit"
  put "account/password" => "profile#update"
  get "account/addition" => "profile#addition"
  post "account/addition" => "profile#save"
  post "account/cover" => "profile#cover"

  devise_for :users, :path => "account", :controllers => {
    :registrations => :account,
    :sessions => :sessions,
    :omniauth_callbacks => :oauths
  }

  root 'home#index'

  get '/search/:word' => 'home#search', as: 'search'
  get '/about/:slug' => 'help#about', as: 'about'
  get '/help/:slug(/:page)' => 'help#view', as: 'help'

  resources :photos
  resources :comments

  get 'explore/:first(/:second(/:third))' => "categories#index", as: 'explore'

  resources :styles do
    member do
      post 'like'
    end
  end

  resources :bookmark

  resources :items do
    member do
      post 'like'
      delete 'like' => 'items#unlike'
      get 'favorites' => 'bookmark#new'
      post 'favorites' => 'items#favorites'
    end

    collection do
      get 'fetch'
      get 'fans'
      get 'more'
    end
  end

  resources :topics, :path => 'forum' do
    collection do
      get 'node/:id' => 'topics#node', as: 'node'
      get 'topic/:id' => 'topics#show', as: 'topic'
    end
  end

  namespace :cpanel do
    
    root :to => "home#index"
    
    resources :categories, path: 'category'

    resources :sections
    resources :nodes
    resources :topics
    resources :styles do
      collection do
        post 'cancel'
        post 'remove'
        post 'recommend'
      end
    end
    resources :positions
    resources :ads
    resources :catalogs
    resources :pages
    resources :tags

    resources :users do
      collection do
        get 'admin'
      end
    end
    
    resources :tasks do
      collection do
        post 'fetch'
        get 'promotion'
        get 'todaypromo'
        post 'recommend'
        post 'cancel'
      end
    end

    resources :items do
      collection do
        post 'remove'
        post 'cancel'
        post 'moveto'
        post 'free'
        post 'band'
        post 'bind'
        get 'tags'
        post 'pin'
      end
    end
  end

  get "users", :to => "users#index", :as => :users
  
  resources :users, :path => "" do
    member do
      get :items
      get :likes
      get :followers
      get :following
      get :topics
    end

    post "follow" => :follow
    delete "follow" => :unfollow
  end

  

end

app/controllers/cpanel/ads_controller.rb
class Cpanel::AdsController < Cpanel::ApplicationController
  
  before_action :find, only: [:edit, :update, :destroy]
  #before_action :convert_datetime_to_int,  only:[:update, :create]

  def index
    @ads = Ad.recent.includes(:position).paginate(per_page: 16, page: params[:page])
  end

  def edit
  end

  def update
    @ad.cover = params[:ad][:cover]
    if @ad.update_attributes ad_params
      redirect_to cpanel_ads_path, notice: 'update an advertisement success'
    else
      render 'edit'
    end
  end

  def new
    @ad = Ad.new
  end

  def create
    ps = Position.find(params[:ad][:position_id])
    @ad = ps.ads.build(ad_params)
    @ad.cover = params[:ad][:cover]
    @ad.user_id = current_user.id

    if @ad.save
      redirect_to cpanel_ads_path, notice: 'new an advertisement success'
    else
      render 'new'
    end
  end

  def destroy
    @ad.destroy
    redirect_to cpanel_ads_path, notice: 'remove an advertisement'
  end

  protected

  def ad_params
    params.require(:ad).permit(:title, :url, :start_on, :expires_on, :description, :position_id)
  end

  def find
    @ad = Ad.find(params[:id])
    render_404 if @ad.nil?
  end

  def convert_datetime_to_int
   DateTime.new(params['start_on(1i)'],
                                     params['start_on(2i)'],
                                     params['start_on(3i)'],
                                     params['start_on(4i)'],
                                     params['start_on(5i)']).to_time.to_i

    DateTime.new(params['expires_on(1i)'],
                                 params['expires_on(2i)'],
                                 params['expires_on(3i)'],
                                 params['expires_on(4i)'],
                                 params['expires_on(5i)']).to_time.to_i
  end
end

app/controllers/cpanel/application_controller.rb
# coding: utf-8
class Cpanel::ApplicationController < ApplicationController
  layout "cpanel"
  
  before_filter :authenticate_user!
  before_filter :require_admin

  def require_admin
    if !current_user.admin
      render_403
    end
  end

end

app/controllers/cpanel/catalogs_controller.rb
class Cpanel::CatalogsController < Cpanel::ApplicationController
  before_filter :find, only: [:edit, :destroy, :update]
  
  def index
    @catalogs = Catalog.roots.order('sort asc')
  end

  def new
    @catalog = Catalog.new
  end

  def edit
  end

  def update
    if @catalog.update_attributes(catalog_params)
      redirect_to cpanel_catalogs_path, notice: "#{@catalog.name} have been updated successfully"
    else
      render :edit
    end
  end

  def create
    @catalog = Catalog.new(catalog_params)

    if @catalog.save
      redirect_to cpanel_catalogs_path, notice: 'new catalog success'
    else
      render 'new'
    end
  end

  def destroy
    @catalog.destroy
    redirect_to cpanel_catalogs_path, notice: "#{@catalog.name} Have been removed successfully"
  end

  protected

  def catalog_params
    params.require(:catalog).permit(:name, :parent_id, :slug, :sort)
  end

  def find
    @catalog = Catalog.find(params[:id])
  end
end

app/controllers/cpanel/categories_controller.rb
class Cpanel::CategoriesController < Cpanel::ApplicationController

  before_filter :find, only: [:edit, :destroy, :update]
  
  def index
    @categories = Category.all.order('sort asc')
  end

  def new
    @category = Category.new
    @category.parent = params[:parent] and params[:parent].to_i ? params[:parent].to_i : 0
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to cpanel_categories_path, notice: "#{@category.name} have been updated successfully"
    else
      render :edit
    end
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to cpanel_categories_path, notice: 'new category success'
    else
      render 'new'
    end
  end

  def destroy
    @category.destroy if @category
    redirect_to cpanel_categories_path, notice: " Have been removed successfully"
  end

  protected

  def category_params
    params.require(:category).permit(:name, :parent, :slug, :sort, :recommend, :display)
  end

  def find
    @category = Category.where(['id=?', params[:id]]).first
  end
end

app/controllers/cpanel/home_controller.rb
class Cpanel::HomeController < Cpanel::ApplicationController
  def index
    
  end
end

app/controllers/cpanel/items_controller.rb
require 'will_paginate/array'

class Cpanel::ItemsController < Cpanel::ApplicationController

  before_filter :set_return_page

  def index
    @items = Item.all.includes([:user, :category])
    if params[:c] and params[:c].to_i != 0
      @items = @items.where('catalog like ?', "#{params[:c]}%")
    end
    if not params[:q].blank?
      @items = @items.where('title like ?', "%#{params[:q]}%")
    end
    @items = @items.order('id desc').paginate(per_page: 15, page: params[:page])
  end

  def destroy
    Item.find(params[:id]).destroy
    redirect_to cpanel_items_path(page: params[:page]), notice: 'remove an item success'
  end

  def tags
    @item = Item.find(params[:id])
    @selected = @item.tags.select('tags.id').map{|x| x.id}
    @tags = Tag.where('available',true).paginate(per_page: 15, page: params[:page])
    render 'tags', layout: false
  end

  def bind
    item = params[:item][:id]
    if params[:id]
      tags = params[:id].map{|id| {tag_id: id, item_id: item} }
      if params[:do] == 'bind'
        ItemsOfTag.create tags
      else
        ItemsOfTag.where(["item_id=? and tag_id in (?)", item, params[:id]]).delete_all
      end
    end
    redirect_to tags_cpanel_items_path(page: params[:page], id: item), notice: 'set tags success'
  end

  def band
  end

  def cover
    Item.where('provider is null').select('id,user_id,url').each do |item|
      begin
        if item.url.nil?
          item.destroy
          Rails.logger.info "#{item.id} deleted"
          next
        end

        uri = URI(item.url)
        host = uri.hostname.split('.')[1].downcase

        case host
        when 'jd'
          item.iid = uri.path.gsub /\D+/,''
        when 'taobao', 'tmall'
          item.iid = /id=(\d+)/.match(uri.query)[1]
          item.url = item.url.split('?')[0] << '?id=' << item.iid.to_s
        else
          iid = 0
        end
        item.provider = host
        item.save
      rescue Exception => e
        item.destroy
        Rails.logger.info e.message
      end
    end
    render text: 'done'
  end

  def pin
    Item.where('id in (?)', params[:id]).update_all('status=status+1')
    redirect_to cpanel_items_path(page: params[:page] || 1), notice: 'Set all selected items to pin in homepage'
  end

  def cancel
    Item.where('id in (?)', params[:id]).update_all('status=0')
    redirect_to cpanel_items_path(page: params[:page] || 1), notice: 'Cancel all selected items to pin in homepage'
  end

  def moveto
    category = params['catalog'].split(',')[-1]
    Item.where(id: params[:id]).update_all(catalog: params[:catalog], category_id: category)
    redirect_to cpanel_items_path(page: params[:page]), notice: 'All selected items were moved to category'
  end

  def remove
    Item.destroy_all(id: params[:id])
    redirect_to cpanel_items_path(page: params[:page]), notice: 'remove success'
  end

  private

  def reset_photo
    file = File.open('p.txt', 'w')

    Photo.where(subject_type: 'Item').includes(:subject).each do |p|
      
      begin
        # The item was removed
        if p.subject.nil?
          #FileUtils.remove_dir "#{Rails.root}/public/users/#{p.user_id}/ph"
          p.destroy
          file.puts "#{p.subject_id} lost"
        else
          # Copy old file to dest
          if p.file.nil?
            p.delete
            file.puts "#{p.id} not file uploaded"
          else
            old = "#{Rails.root}/public/users/#{p.user_id}/photo/#{p.id}/#{p.file.file.basename}.#{p.file.file.extension}"
            #file.puts old
            if File.exists? old
              FileUtils.mkdir_p File.dirname p.file.file.path
              FileUtils.mv old, p.file.file.path
              file.puts "copy #{old} to #{p.file.file.path}"
            else
              file.puts "#{old} not found"
            end
          end
        end
      rescue Exception => e
        file.puts e.message
        file.puts "#{p.subject_id} #{p.id}"
      end

    end

    render text: 'done'
  end

  def _reset_cover
    file = File.open('cover.txt', 'w')
    Item.all.each do |item|
      begin
        if !item.cover.file.exists?
          photo = item.photos.first
          if photo.file.file.exists?
            item.cover = File.new( photo.file.path )
            item.save
          else
            file.puts "#{item.id} with #{photo.id} cover not set"
          end          
        end
      rescue Exception=> e
        file.puts e.message
        file.puts item.id
      end
    end
    file.close
    render text: 'finish'
  end

  def set_return_page
    params[:page] = params[:page].to_i > 0 ? params[:page] : 1
  end
end

app/controllers/cpanel/nodes_controller.rb
# coding: utf-8
class Cpanel::NodesController < Cpanel::ApplicationController

  def index
    @nodes = Node.sorted
  end

  def show
    @node = Node.find(params[:id])
  end

  def new
    @node = Node.new
  end

  def edit
    @node = Node.find(params[:id])
  end

  def create
    @node = Node.new(params[:node].permit!)

    if @node.save
      redirect_to(cpanel_nodes_path, :notice => 'Node was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @node = Node.find(params[:id])

    if @node.update_attributes(params[:node].permit!)
      redirect_to(cpanel_nodes_path, :notice => 'Node was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    redirect_to(cpanel_nodes_url)
  end
end

app/controllers/cpanel/pages_controller.rb
class Cpanel::PagesController < Cpanel::ApplicationController
  before_action :find, only: [:edit, :update, :destroy]

  def index
    @posts = Page.paginate(per_page: 16, page: params[:page])
  end

  def new
    @post = Page.new
  end

  def edit
  end

  def update
    if @post.update_attributes(page_params)
      redirect_to cpanel_pages_path, notice: 'update a post success'
    else
      render 'edit'
    end
  end

  def create
    @post = Page.new(page_params)
    if @post.save
      redirect_to cpanel_pages_path, notice: 'new post success'
    else
      render 'new'
    end
  end

  def destroy
    @post.destroy
    redirect_to cpanel_pages_path, notice: 'remove a post success'
  end

  protected

  def page_params
    params.require(:page).permit(:title, :catalog_id, :keywords, :description,  :body)
  end

  def find
    @post = Page.find(params[:id])
  end
end

app/controllers/cpanel/positions_controller.rb
class Cpanel::PositionsController < Cpanel::ApplicationController

  before_action :find, only: [:edit, :update, :destroy]

  def index
    @positions = Position.recently.paginate(per_page: 16, page: params[:page])
  end

  def new
    @position = Position.new
  end

  def edit
  end

  def update
    if @position.update_attributes(position_params)
      redirect_to cpanel_positions_path, notice: 'update a position success'
    else
      render 'edit'
    end
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to cpanel_positions_path, notice: 'new position success'
    else
      render 'new'
    end
  end

  def destroy
    @position.destroy
    redirect_to cpanel_positions_path, notice: 'remove a position success'
  end

  protected

  def position_params
    params.require(:position).permit(:title, :slug, :width, :height, :description)
  end

  def find
    @position = Position.find(params[:id])
  end
end

app/controllers/cpanel/sections_controller.rb
class Cpanel::SectionsController < Cpanel::ApplicationController
  
  before_filter :find, except: [:index, :new, :create]

  def index
    @sections = Section.all.order('sort')
  end

  def edit
  end

  def new
    @section = Section.new
  end

  def update
    if @section.update_attributes(section_params)
      redirect_to cpanel_sections_path, notice: "#{@section.name} have been updated successfully"
    else
      render :edit
    end
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to cpanel_sections_path, notice: 'new section success'
    else
      render 'new'
    end
  end

  def destroy
    @section.destroy
    redirect_to cpanel_sections_path, notice: "#{@section.name} Have been removed successfully"
  end

  protected

  def section_params
    params.require(:section).permit(:name, :sort)
  end

  def find
    @section = Section.find(params[:id])
  end
end

app/controllers/cpanel/styles_controller.rb
require 'will_paginate/array'

class Cpanel::StylesController < Cpanel::ApplicationController
  
  def index
    @styles = Style.all(:include => [:user], order: 'id desc').paginate(per_page: 15, page: params[:page])
  end

  def remove
    #Style.where(['id in (?)', params[:id] ]).destroy
    redirect_to cpanel_styles_path, notice: 'remove style success'
  end

  # do as set recommend
  def recommend
    Style.update_all('recommend=1', ['id in (?)', params[:id] ])
    redirect_to cpanel_styles_path, notice: 'set styles as recommend'
  end

  def cancel
    Style.update_all('recommend=0', ['id in (?)', params[:id]])
    redirect_to cpanel_styles_path, notice: 'cancel styles as recommend'
  end

end

app/controllers/cpanel/tags_controller.rb
class Cpanel::TagsController < Cpanel::ApplicationController

  before_action :find, only:[:edit,:update,:destroy]

  def index
    @tags = Tag.all.includes([:category]).paginate(per_page: 20, page: params[:page])
  end

  def edit
  end

  def new
    @tag = Tag.new
  end

  def destroy
    @tag.destroy if @tag
    
  end

  def update
    if @tag.update_attributes(tag_params)
      redirect_to cpanel_tags_path, notice: 'update a tag success'
    else
      render 'edit'
    end
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to cpanel_tags_path, notice: 'new tag success'
    else
      render 'new'
    end
  end

  protected
  def find
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :available, :searchable,:recommend, :category_id)
  end
end

app/helpers/cpanel/ads_helper.rb
module Cpanel::AdsHelper
end

app/helpers/cpanel/catalogs_helper.rb
module Cpanel::CatalogsHelper
end

app/helpers/cpanel/positions_helper.rb
module Cpanel::PositionsHelper
end

app/views/cpanel/items/index.html.erb
<%= simple_form_for([:cpanel, Item.new], html:{ id: 'form',class: 'form-inline' }) do %>
<input type="hidden" name="page" value="<%= params[:page];%>" />
<table>
  <tr>
    <td style="padding:0"><div class="q-box"><input type="text" name="q" class="form-control" value="<%= params[:q]%>"></div></td>
    <td style="padding:0"><div class="cat-box"><select id="catalog" name="c"></select></div></td>
    <td><button class="btn btn-default" onclick="post('./items', 'get');" type="button">查找</button></td>
  </tr>
</table>

<table class="table" width="100%" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th width="30">
        <input type="checkbox" name="all" id="chkall">
      </th>
      <th width="64">小图</th>
      <th>宝贝名称</th>
      <th width="120">所属分类</th>
      <th width="80">喜欢/浏览</th>
      <th width="80">用户</th>
      <th width="100">发布时间</th>
      <th width="80" >状态</th>
      <th width="120"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |o| %>
    <tr>
      <td >
        <input type="checkbox" id="chk<%= o.id %>" name="id[]" value="<%=o.id %>">
      </td>

      <td>
        <%= image_tag o.cover.default.url, size: '50x50' %>
      </td>
      <td><%= link_to o.title, item_path(o.id), target: '_blank' %></td>
      <td><%= o.category.nil? ? '' : o.category.name %></td>
      <td><%= "#{o.likes_count}/#{o.views_count}" %></td>
      <td><%= o.user.try(:login) %></td>
      <td><%= o.created_at.strftime("%Y-%m-%d") %></td>
      <td><%= o.status > 0 ? '收入' : '采集' %></th>
      <td>
        <a href="javascript:;" class="tag" id="<%= o.id%>">标签</a>
        <a href="#operation" class="cat" data-id="<%=o.id%>">设置分类</a>
      </td>
    </tr>
    <% end %>

    <tfoot>
      <td colspan="9">
        <div class="btn-group">
          <div class="cat-box">
            <select name="catalog" id="category"></select>
          </div>
          <a name="operation"></a>
          <button type="button" class="btn btn-warning" onclick="post('./items/moveto');">移动分类</button>
          <button type="button" class="btn btn-danger" onclick="post('./items/remove');">删除</button>
          <button type="button" class="btn btn-primary" onclick="post('./items/cancel');">取消</button>
          <button type="button" class="btn btn-success" onclick="post('./items/pin');">推荐</button>
        </div>
      </td>
    </tfoot>
  </tbody>
</table>
<% end %>

<%= will_paginate @items%>

<div class="modal fade " id="pop">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">选择标签</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

<!-- The template to display files available for upload -->
<script id="template-category" type="text/x-tmpl">
  <tr>
    {% for( var i=0; i < o.depth; i++ ) { %}
    <td></td>
    {% } %}

    <td colspan="{%= o.max - o.depth %}">
        {%=o.name%}
    </td>
    <td>
        {% if(o.child.length == 0){ %}
        <input type="checkbox" name="id[]" value="{%= o.id%}" />
        {% } %}
    </td>
  </tr>
</script>

<!-- Treeview -->
<%= render 'cpanel/categories/treeview' %>

<%= content_for :scripts do %>
<script src="/scripts/tmpl.min.js"></script>
<script type="text/javascript">
SelectView.multiValue = 1;
SelectView.render(tree['tree'], 'category', <%= params[:catalog].blank? ? 0 : params[:catalog].split(',')[-1] %>);
SelectView.render(tree['tree'], 'catalog', <%= params[:c].blank? ? 0 : params[:c].split(',')[-1] %>);

var max = tree['depth'],
    tbody = $('#tree tbody');

function render_node(tree, depth){
  for(var i=0; i < tree.length; i++){
    node = tree[i];
    node['depth'] = depth;
    node['max'] = max;
    tbody.append( tmpl('template-category', node) );
    if (node['child'].length > 0) render_node(node['child'], depth+1)
  }
}
$('#tree thead tr th').eq(1).attr('colspan', max);
render_node(tree['tree'], 0);

$('.cat').on('click', function(){
  $('#chk' + $(this).attr('data-id')).attr('checked', true);
  return true;
});

$('.tag').on('click', function(){
  $('#pop .modal-body').html('<iframe name="itag" src="/cpanel/items/tags?id='+ $(this).attr('id')+'" width="100%" height="100%" frameborder="0"></iframe>');
  $('#pop').modal();
});

// ajax post on close the pop
$('#pop #finish').on('click', function(){
  var id = $('input[type="checkbox"]', window.frames["itag"].document);
});

function post(url){
  $('#form').attr('action', url);
  if( arguments.length > 1) $('#form').attr('method', 'get');
  $('#form').submit();
}
</script>
<% end %>

app/views/cpanel/items/tags.html.erb
<%= simple_form_for([:cpanel, @item], :url => bind_cpanel_items_path, html:{ method: 'post' }) do |f| %>
<%= f.input :id, as: 'hidden' %>
<table class="table" width="100%" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
    <tr>
      <td width="15"><input type="checkbox" name="id[]" value="<%=tag.id%>" <%= @selected.include?(tag.id) ? 'checked' : '' %> /></td>
      <td>
        <%= tag.name %>
      </td>
    </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="2">
        <div class="btn-group btn-group-xs">
          <button type="submit" class="btn btn-primary" name="do" value="bind">设置标签</button>
          <button type="submit" class="btn btn-warning" name="do" value="unbind">取消设置</button>
        </div>
      </td>
    </tr>
  </tfoot>
</table>
<% end %>